In [1]:
!pip3 install pandas openpyxl

Requirement already satisfied: pandas in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.23.2 in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.1)
Requirement already satisfied: et-xmlfile in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\maxim\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

WARNING: Ignoring invalid distribution ~orch (C:\Users\maxim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\maxim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\maxim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\maxim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\maxim\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel('dataset.xlsx', engine='openpyxl')
df = df.iloc[:, :-1]
df.head(5)

,ФИО,Кол-во Детей,Unnamed: 2,Вареники,Блины,Манты,Гедза,Мясо,Зелень,Фаст-фуд,...,Топливо,авто,Яндекс,Сбер,Вуш,Кап.ремонт,Мусор,Вода,Свет,Отопление
0,Абрамов Фёдор Степанович,5,4771,6441,2129,7262,6571,6571,4226,4985,...,5090,897,7938,5679,3479,7336,108,1409,9445,3812
1,Абрамов Андрей Даниилович,5,2259,9288,3941,6429,9012,5653,3221,3619,...,3314,1186,786,7522,3326,5589,9161,6603,8131,4567
2,Абрамов Михаил Игоревич,1,4623,4318,2799,5582,8064,1091,5836,6773,...,1493,8121,5875,138,9458,4004,5965,3088,5568,9117
3,Абрамов Глеб Львович,2,7853,642,6408,8347,4399,3337,2268,4969,...,3199,3341,385,3867,6963,9375,4460,4017,5387,3024
4,Абрамов Николай Артёмович,2,4903,6350,336,1969,8981,6215,2070,7829,...,6022,1769,8516,4184,4447,7437,6729,8728,8604,9872

In [3]:
column_list = df.columns.tolist()
column_list = list(df.columns)
column_list = column_list[2:]
column_list

['Unnamed: 2',
 'Вареники',
 'Блины',
 'Манты',
 'Гедза',
 'Мясо',
 'Зелень',
 ' Фаст-фуд',
 'Роллы',
 ' Пицца',
 'Черноголовка',
 ' Пепси',
 'Колла',
 'Фанта',
 'Спрайт',
 'Ибупрофен',
 'Ношпа',
 'Омепразол',
 'Фуросимед',
 'Амплодин',
 'Хоккей',
 'Активный отдых',
 'Футбол',
 'Бассейн  ',
 'Танцы',
 ' Водка',
 'Пиво',
 'Топливо',
 'авто',
 'Яндекс',
 'Сбер',
 'Вуш',
 'Кап.ремонт',
 'Мусор',
 'Вода',
 'Свет ',
 'Отопление']

In [4]:
df['общие_расходы'] = df[column_list].sum(axis=1)
df.head(500)

,ФИО,Кол-во Детей,Unnamed: 2,Вареники,Блины,Манты,Гедза,Мясо,Зелень,Фаст-фуд,...,авто,Яндекс,Сбер,Вуш,Кап.ремонт,Мусор,Вода,Свет,Отопление,общие_расходы
0,Абрамов Фёдор Степанович,5,4771,6441,2129,7262,6571,6571,4226,4985,...,897,7938,5679,3479,7336,108,1409,9445,3812,192963
1,Абрамов Андрей Даниилович,5,2259,9288,3941,6429,9012,5653,3221,3619,...,1186,786,7522,3326,5589,9161,6603,8131,4567,177338
2,Абрамов Михаил Игоревич,1,4623,4318,2799,5582,8064,1091,5836,6773,...,8121,5875,138,9458,4004,5965,3088,5568,9117,209376
3,Абрамов Глеб Львович,2,7853,642,6408,8347,4399,3337,2268,4969,...,3341,385,3867,6963,9375,4460,4017,5387,3024,170114
4,Абрамов Николай Артёмович,2,4903,6350,336,1969,8981,6215,2070,7829,...,1769,8516,4184,4447,7437,6729,8728,8604,9872,199692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Архипов Максим Тихонович,5,3338,1250,6578,3027,5690,7014,6893,3786,...,4341,507,6840,2966,3895,9662,4012,3923,2260,162222
496,Архипов Алексей Денисович,4,3264,1091,590,8100,4432,9715,4031,8418,...,8901,1159,7692,7799,4368,4921,4037,8801,7706,199688
497,Архипов Илья Егорович,3,4739,8274,2554,3876,5592,978,5010,8527,...,1520,132,5542,6153,7944,5466,3154,8085,8369,202868
498,Архипова Полина Дмитриевна,2,6478,730,5088,8052,596,2126,1123,2311,...,5593,760,7300,350,661,7991,3758,1574,846,145293
499,Архипова Александра Павловна,4,995,8840,4618,622,3283,2752,2216,4247,...,9386,9468,4191,5094,1445,4981,8573,202,6310,189272

In [5]:
conditions = [
    df['общие_расходы'] < 150000,
    (df['общие_расходы'] >= 150000) & (df['общие_расходы'] < 180000),
    df['общие_расходы'] >= 180000
]
df['категория_дохода'] = np.select(conditions, ['Низкий', 'Средний', 'Высокий'])
df.head(100)

,ФИО,Кол-во Детей,Unnamed: 2,Вареники,Блины,Манты,Гедза,Мясо,Зелень,Фаст-фуд,...,Яндекс,Сбер,Вуш,Кап.ремонт,Мусор,Вода,Свет,Отопление,общие_расходы,категория_дохода
0,Абрамов Фёдор Степанович,5,4771,6441,2129,7262,6571,6571,4226,4985,...,7938,5679,3479,7336,108,1409,9445,3812,192963,Высокий
1,Абрамов Андрей Даниилович,5,2259,9288,3941,6429,9012,5653,3221,3619,...,786,7522,3326,5589,9161,6603,8131,4567,177338,Средний
2,Абрамов Михаил Игоревич,1,4623,4318,2799,5582,8064,1091,5836,6773,...,5875,138,9458,4004,5965,3088,5568,9117,209376,Высокий
3,Абрамов Глеб Львович,2,7853,642,6408,8347,4399,3337,2268,4969,...,385,3867,6963,9375,4460,4017,5387,3024,170114,Средний
4,Абрамов Николай Артёмович,2,4903,6350,336,1969,8981,6215,2070,7829,...,8516,4184,4447,7437,6729,8728,8604,9872,199692,Высокий
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Акимов Максим Кириллович,1,6888,8537,4413,7900,1438,124,9430,6158,...,5893,4333,2566,975,8788,1899,7153,1680,209288,Высокий
96,Акимов Дмитрий Дмитриевич,4,8701,1251,2978,9143,769,2111,323,834,...,675,9817,1348,9782,2372,2780,4770,5346,164700,Средний
97,Акимов Тимур Даниилович,3,4275,6010,674,1807,813,2844,2862,7521,...,693,1790,9982,3487,3390,5072,1069,7142,181391,Высокий
98,Акимов Андрей Иванович,4,1911,5281,3369,2998,3946,4898,7093,1118,...,4514,4174,9645,9709,2749,5555,828,5515,163686,Средний
99,Акимов Даниил Кириллович,2,1443,7174,1458,9062,384,3508,6427,4584,...,2353,2783,7632,3208,2695,8207,4071,9726,182826,Высокий